// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf4pt3gZyuJRW_r9DwOpVwlEpQMn_ub8I',
    appId: '1:998372203288:web:2479a8cfc22223ec711c6d',
    messagingSenderId: '998372203288',
    projectId: 'vivamais-550f1',
    authDomain: 'vivamais-550f1.firebaseapp.com',
    storageBucket: 'vivamais-550f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMDXtFXsOkOHswLE0DteH3IvE62S_W9s',
    appId: '1:998372203288:android:d2e000b4669c3e39711c6d',
    messagingSenderId: '998372203288',
    projectId: 'vivamais-550f1',
    storageBucket: 'vivamais-550f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKBjW4Uyw9xYzoMVM_x7CzDH5F8Ti4Ww',
    appId: '1:998372203288:ios:8ade9bdc004d9964711c6d',
    messagingSenderId: '998372203288',
    projectId: 'vivamais-550f1',
    storageBucket: 'vivamais-550f1.firebasestorage.app',
    iosBundleId: 'com.example.vivaMais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKBjW4Uyw9xYzoMVM_x7CzDH5F8Ti4Ww',
    appId: '1:998372203288:ios:8ade9bdc004d9964711c6d',
    messagingSenderId: '998372203288',
    projectId: 'vivamais-550f1',
    storageBucket: 'vivamais-550f1.firebasestorage.app',
    iosBundleId: 'com.example.vivaMais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf4pt3gZyuJRW_r9DwOpVwlEpQMn_ub8I',
    appId: '1:998372203288:web:e6d6bb837b17bb7b711c6d',
    messagingSenderId: '998372203288',
    projectId: 'vivamais-550f1',
    authDomain: 'vivamais-550f1.firebaseapp.com',
    storageBucket: 'vivamais-550f1.firebasestorage.app',
  );
}
